# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('column_name', models.CharField(max_length=100)),
                ('column_type', models.CharField(max_length=100)),
                ('sequence_column', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTables',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='columns',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyltb.UserTables'),
        ),
    ]
