# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyltb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columns',
            old_name='sequence_column',
            new_name='column_sequence',
        ),
        migrations.RenameField(
            model_name='columns',
            old_name='table_id',
            new_name='table',
        ),
    ]
